### PR TITLE
Revert "fix: check node for null before running visitor"

### PR DESCRIPTION
**Pull request by jacobator**
Reverts Redocly/openapi-cli#200

### CODE REVIEW

**Comment by Marshevskyy** [comment]
@jacobator then how to be with https://github.com/Redocly/openapi-cli/issues/195 ?

**Comment by RomanHotsiy** [comment]
@Marshevskyy we don't care about https://github.com/Redocly/openapi-cli/issues/195.

#200 introduced a much much worse issue. We have to revert it so it won't go into the release.

**Comment by Marshevskyy** [comment]
@RomanHotsiy I've just reopened https://github.com/Redocly/openapi-cli/issues/195. Please put a priority label to it

**Comment by Marshevskyy** [comment]
@jacobator does it fix https://github.com/Redocly/openapi-cli/issues/252? if so, please add it to a description as well. thx

**Review by Marshevskyy — APPROVED** [review]

**Comment by jacobator** [comment]
> @jacobator does it fix #252? if so, please add it to a description as well. thx

They are not connected, but I have to revert it before publishing https://github.com/Redocly/openapi-cli/issues/252 because https://github.com/Redocly/openapi-cli/pull/200 shouldn't be released.

**Pull request merged**
