### PR TITLE
Update the year to 2021 and Add License Header

### PR DESCRIPTION
**Pull request by pawelborkar**
I have updated the year from 2019 to 2021 and also added **MIT License**  header to the license to make more clear and updated.

### CODE REVIEW

**Comment by adamaltman** [comment]
We were advised the license should reflect the year it was originally written.

**Comment by andriyl** [comment]
@pawelborkar could you change the year from 2021 to 2019, please?

**Comment by pawelborkar** [comment]
@andriyl  This PR wasn't accepted so the main license file has no change in it and reflects the year 2019.

>We were advised the license should reflect the year it was originally written.

I think it's better to close this PR.

**Comment by andriyl** [comment]
@pawelborkar thank you

**Pull request closed without merging**
